config/routes.rb
Rails.application.routes.draw do
  resources:posts
  get 'welcome/index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	has_attached_file :image, styles: { :medium => "300x400#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate, :except => [ :index, :show ] 
	before_action :find_post, only: [:show,:edit,:update,:destroy]
	
	def index
		@posts =Post.all
	end

	def new
		@post= Post.new
	end

	def create
		@post =Post.new post_params

		if @post.save
			redirect_to @post,notice:"Good job Peter!Your article was saved"
		else
			render "new",notice:"Oh no,Peter!I was unable so save the post"
		end
	end

	def show
	end	

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice:"Your article was successfully saved!"
		else
			render "edit"
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	

	private
	def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "secret"
    end
  	end

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end

	def find_post
		@post =Post.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@post =Post.all.order("created_at desc").take(1)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>RadulescuPETRU</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Cache-Control" content="max-age=200" />
	<link rel="shortcut icon" href="assets/favicons/favicon.ico">
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<% if @post.errors.any? %>

		<h2><%= pluralize(@post.errors.count,"error") %> prevented this post from savng:</h2>

		<ul>
			<%= @post.errors.full_messages.each do |msg| %>
				<li><%= msg %> </li>
				<% end %>
		</ul>

	<%end%>
	
	<%= f.label :title %><br>
	<%= f.text_field(:title,:style => "width:400px") %>

	<br>
	<br>

	<%= f.label :content ,"Write your article here" %><br>
	<%= f.text_area(:content,:class => "text-area-size") %>	
	<%= f.file_field(:image,:class => "image-area") %>
	<br>
	<br>

	<div class="submit-button">
	<%= f.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<section class="new-post-page">
<h3 class="new-post">Edit Post</h3>
<div class="new-post-form">
<%= render 'form'%>
</div>
</section>

app/views/posts/index.html.erb
<div class="page-wrapper">
	<header class="index-header">
		<%= link_to root_path do %>
				<div class="logo"></div>
		<% end %>
	</header>


	<section class="index-body">
		<div class="posts-body">
			<% @posts.each do |post| %>
				<div class="post-box">
					<%= image_tag post.image.url(:medium) %>
					<div class="post-info">
						<a class="post-title"><%= post.title %></a>		
						<%= link_to "Read Post",post , :class => "read-button"%>
					</div>
				</div>
			<%end %>
		</div>
	</section>


	<footer class="index-footer">
		<a href="mailto:petruradulescu.v@gmail.com" class="mail">petruradulescu.v@gmail.com</a>
		<ul class="post-social">
			<li><a href="https://www.facebook.com/R.PETRUnd" class="post-fb">facebook</a></li>
			<li><a href="https://twitter.com/PetruRadulescu" class="post-tw">twitter</a></li>
		</ul>
	</footer>
</div>





app/views/posts/new.html.erb
<section class="new-post-page">
<h3 class="new-post">Write your new post</h3>
<div class="new-post-form">
<%= render 'form' %>
</div>
</section>

app/views/posts/show.html.erb
<div class="show-wrapper">
	<header class="post-header">
	      <%= link_to posts_path do %>
  			<div class="logo"></div>
			<% end %>
	      <div class="update-buttons">
	      	<%= link_to "Edit" , edit_post_path(@post)%>
			<%= link_to "Delete" , post_path(@post), method: :delete,data:{confirm:"Are you sure you want to delete the post?"} %>
	      </div>
	</header>
	<section class="show-body">
		<div class="show-image">
			<%= image_tag @post.image.url() %>
		</div>
		
		<h2 class="show-title"><%= @post.title %> </h2>
		<div class="show-content">
			<%= simple_format @post.content %>
		</div>
	</section>
</div>

app/views/welcome/index.html.erb
<div class="home-wrap">
      <div class="mobile-nav">
              <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#9gag">9GAG</a></li>
                <li><a href="#social">Social</a></li>
                <li><a href="#artwork">Artwork</a></li>
                <li><a href="#blog">Blog </a></li>
                <li><%= link_to "New Post",new_post_path  %></li>
                <li><a href="#contact">Contact</a></li>
              </ul>
      </div>
      <header class="main">
        <div class="header-position">
          <div class="logo"></div>
          <nav class="site-nav"> 
                  <ul>
                    <li><a href="#about">About</a></li>
                    <li><a href="#9gag">9GAG</a></li>
                    <li><a href="#social">Social</a></li>
                    <li><a href="#artwork">Artwork</a></li>
                    <li><a href="#blog">Blog </a></li>
                    <li><%= link_to "New Post",new_post_path  %></li>
                    <li><a href="#contact">Contact</a></li>
                  </ul>
          </nav><a href="mailto:petruradulescu.v@gmail.com" class="email-link">+email-me</a>
          <div class="mobile-nav-toggle"><span></span></div>
        </div>
      </header>
      <div class="home-sections">
        <section id="about" class="about">
          <div class="flex flex--center">
            <div class="col-1 push-right">
              <h2>Petru is trying to grow up,</h2>
              <p class="home-lead">but instead he spends his time...</p>
            </div>
          </div>
        </section>
        <section id="9gag" class="gag">
          <div class="flex flex--space-around">
            <div class="col-1">
              <div class="picture-strip"></div>
              <div class="flex-video"><img id="imgAnimate"></div>
            </div>
            <div class="col-1 order-first">
              <p class="home-lead outdented">...creating funny memes on 9GAG...</p><a href="http://9gag.com/u/petruradulescuv" class="home-cta">See on 9GAG</a>
            </div>
          </div>
        </section>
        <section id="social" class="social">
          <div class="flex flex--center">
            <div class="col-50 flex flex--center facebook">
              <div class="col-1">
                <p class="home-lead">...being active on Facebook...</p><a href="https://www.facebook.com/berlinartparasites/photos/a.320868767963056.66054.199504240099510/937453126304614/?type=3&amp;theater/" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/facebook1.jpg"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Surround yourself with the dreamers and the doers, the believers and the thinkers.</p>
                            </div>
                          </div></a><a href="https://www.facebook.com/reddit/posts/10153895398323735" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/facebook2.png"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Hangover cures from Reddit. You're welcome.</p>
                            </div>
                          </div></a><a href="https://www.facebook.com/8fact/posts/423565864504220:0" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/facebook3.png"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Listening to music is one of the few activities that uses the entierly of the human brain</p>
                            </div>
                          </div></a>
                <div class="cf">   </div><a href="" class="home-cta">Facebook</a>
              </div>
            </div>
            <div class="col-50 flex flex--center twitter">
              <div class="col-1">
                <p class="home-lead">...and Twitter...</p><a href="https://twitter.com/PetruRadulescu/status/677479790560022528" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/tweet1.jpg"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Help Beethoven arrange his masterpieces in today`s #GoogleDoodle</p>
                            </div>
                          </div></a><a href="https://twitter.com/DevTipsShow/status/684041869983125504" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/tweet2.png"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Reviewing last year's devtips annual report. Getting ready to make goals for 2016</p>
                            </div>
                          </div></a><a href="https://twitter.com/TravAndLos/status/676806263888437249" target="blank" class="design-img-link">
                          <div class="box">
                            <div class="row-1 thumb">
                              <div class="col-20"><img src="/assets/social/tweet3.png"></div>
                              <div class="col-80">
                                <p class="view">View post</p>
                              </div>
                            </div>
                            <div class="row-1 message">
                              <p>Do you meditate? It's not as hard as you might think. This week we talk about the value of reflection</p>
                            </div>
                          </div></a>
                <div class="cf"></div><a href="" class="home-cta">Twitter</a>
              </div>
            </div>
          </div>
        </section>
        <section id="artwork" class="artwork">
          <div class="row-50 portfolio">
                    <div class="design-box"><img src="/assets/social-img/1.png" class="design-image">
                      <div class="overlay"> 
                        <div class="text">
                          <p>This is a self-portrait I`ve made for fun and also to consolidate my Adobe Illustrator skills.</p>
                        </div>
                        <div class="cta-buttons">
                          <div class="like">asdasda</div>
                          <div class="more">awda</div>
                        </div>
                      </div>
                    </div>
                    <div class="design-box"><img src="/assets/social-img/3.png" class="design-image">
                      <div class="overlay"> 
                        <div class="text">
                          <p>This is one of my entries in a design contest held my MEGA IMAGE,a big food chain here in Romania.'</p>
                        </div>
                        <div class="cta-buttons">
                          <div class="like">asdasda</div>
                          <div class="more">awda</div>
                        </div>
                      </div>
                    </div>
                    <div class="design-box"><img src="/assets/social-img/6.png" class="design-image">
                      <div class="overlay"> 
                        <div class="text">
                          <p>This is another of my entries in a design contest held my MEGA IMAGE,a big food chain here in Romania.</p>
                        </div>
                        <div class="cta-buttons">
                          <div class="like">asdasda</div>
                          <div class="more">awda</div>
                        </div>
                      </div>
                    </div>
                    <div class="design-box"><img src="/assets/social-img/4.png" class="design-image">
                      <div class="overlay"> 
                        <div class="text">
                          <p>The hoodie is one of the first things I`ve designed and I`m actually proud of how it turned out.</p>
                        </div>
                        <div class="cta-buttons">
                          <div class="like">asdasda</div>
                          <div class="more">awda</div>
                        </div>
                      </div>
                    </div>
                    <div class="design-box"><img src="/assets/social-img/5.png" class="design-image">
                      <div class="overlay"> 
                        <div class="text">
                          <p>This is the web-browser view of a webform for a car service company I`ve designed a while a go. </p>
                        </div>
                        <div class="cta-buttons">
                          <div class="like">asdasda</div>
                          <div class="more">awda</div>
                        </div>
                      </div>
                    </div>
          </div>
          <div class="row-50 artist">
            <p class="home-lead">...making designs for contests and friends...</p>
            <div class="me"></div><a href="" class="home-cta">See full portfolio</a>
          </div>
        </section>
        <section id="blog" class="blog">
          <div class="flex flex--space-around">
            <div class="col-2 last-posts">
              <div class="post-container">


              	<% @post.each do |post| %>
	              	<%=image_tag post.image.url(), :class =>"blog-image" %>
	                <div class="blog-more">
	                  <%= link_to post.title,post ,:class=>"blog-title" %>
	                  <p class="blog-text"><%= truncate(post.content,:length =>190)%></p>
	                  <%= link_to "Read more",post,:class => "home-cta"%>
	                </div>
              	<% end %>



                
              </div>
            </div>
            <div class="col-2 more-posts">
              <p class="home-lead">...sharing his toughts on world,word and life...</p>
              <%= link_to "See all posts",posts_path,:class => "home-cta"%>
            </div>
          </div>
        </section>
        <footer id="contact" class="home-footer"><a href="mailto:petruradulescu.v@gmail.com" class="mail">petruradulescu.v@gmail.com</a></footer>
      </div>
    </div>